name: Check Code Formatting for carla-map libraries

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read

jobs:
  check_cpp:
 
    name: Check Code Formatting

    runs-on: ubuntu-22.04

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
      with:
        egress-policy: audit

    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
          submodules: true

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install clang-format-14

    - name: Check Formatting
      run: failed=0; for file in `find . -path ./dependencies -prune -false -o -iname *.cpp -o -iname *.hpp`; do if [ `clang-format-14 $file -output-replacements-xml | grep -c "<replacement "` -ne 0 ]; then echo "$file does not match codeing style. Please run clang-format-14"; failed=1; fi; if [ $failed -ne 0 ]; then exit 1; fi; done
