name: Build and Test of AD-Map Library

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    name: GCC on Ubuntu 16.04
    
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test && \
           sudo apt-get update && \
           sudo apt-get install -y --no-install-recommends \
                build-essential \
                castxml \
                cmake \
                libboost-all-dev \
                libgtest-dev \
                liblapacke-dev \
                libopenblas-dev \
                libproj-dev \
                libpugixml-dev \
                libpython3-dev \
                python \
                python-setuptools \
                python-pip \
                python-wheel \
                python3 \
                python3-setuptools \
                python3-pip \
                python3-wheel && \
           pip3 install --user -U colcon-common-extensions && \
           pip3 install --user xmlrunner && \
           pip2 install --user pygccxml pyplusplus xmlrunner

    - name: Fetch git submodules
      run: git submodule update --init
      
    - name: Build and Test
      run: GTEST_OUTPUT="xml:test_results" && \
           colcon build --event-handlers console_direct+ --executor sequential --cmake-args -DBUILD_HARDENING=ON -DBUILD_TESTING=ON -DBUILD_PYTHON_BINDING=ON && \
           colcon test --event-handlers console_direct+ --packages-select ad_map_access ad_physics && \
           colcon test-result
